### ISSUE TITLE
Exit App Loading GIF Display Issue

### ISSUE THREAD

**Issue by oDinZu** [DenioD/SilentDragonLite-1#100]
Operating System: Linux Ubuntu 20.04
Application Version: v1.3.1

Clicking the exit button, then application begins to exit, the GIF bugs out; see below.
![Screenshot from 2020-06-05 19-42-07](https://user-images.githubusercontent.com/18726788/83930690-d6c5a000-a766-11ea-9539-f31263e99740.png)

**Comment by DenioD** [comment]
fixed
