### ISSUE TITLE
Limit Number of Characters for Nickname

### ISSUE THREAD

**Issue by oDinZu** [DenioD/SilentDragonLite-1#101]
On adding lots of characters for the nickname, it begins to create ugly GUI with scroll bars. 

![Screenshot from 2020-06-05 15-03-48](https://user-images.githubusercontent.com/18726788/83931041-8ea77d00-a768-11ea-9c04-8abc90a06766.png)

**Comment by DenioD** [comment]
i set it to max 25. Fixed :-)
