### ISSUE TITLE
Rearranging + Duplication of Chat Message Bubbles in HushChat

### ISSUE THREAD

**Issue by oDinZu** [DenioD/SilentDragonLite-1#103]
Operating System: Ubuntu 20.04
Application Version: v1.3.1
Theme: Midnight
Note: Running application in CLI with STDOUT

By left clicking on chat bubble and dragging dropping, we are able to duplicate and rearrange messages. 

Furthermore, on reloading the application or loading another contact messages and going back to original rearranged messages, the chat bubbles are refreshed and display as should. 
![Screenshot from 2020-06-05 22-31-10](https://user-images.githubusercontent.com/18726788/83934115-45f9bf00-a77c-11ea-984e-386f6974d6dd.png)

**Comment by DenioD** [comment]
should be fixed now :-)
