### ISSUE TITLE
Send your friend some Hush Button

### ISSUE THREAD

**Issue by DenioD** [DenioD/SilentDragonLite-1#105]
we should provide the opportunity to send some Hush to a friend with right-click on this contact. Nothing more then the value of Hush should be needed by the user.

**Comment by leto** [comment]
:money_with_wings:

**Comment by UrgeyBergy** [comment]
Would be nice if this was a single button, "Send or Request Hush" where a popup appears prompting if you want to send or request, and then you can add a memo as well

![image](https://user-images.githubusercontent.com/37842843/84041082-69398f80-a971-11ea-8c19-67194eb7c976.png)
