### ISSUE TITLE
Message is Erased in Input Message Box After Sending Message Then Typing Another While Loading

### ISSUE THREAD

**Issue by oDinZu** [DenioD/SilentDragonLite-1#107]
OS: Ubuntu 20.04
Bin: Latest as of todays spacetime
App Version: 1.3.1
Note: built via CLI with STDOUT 

Our message gets erased after typing one message, clicking send, then while animation is loading, typing another message. The message typed while loading animation is active erases text in input box.

**Comment by leto** [comment]
@DenioD what are your thoughts on this bug?

In general, we should try hard to not lose data of our users, including text they entered but haven't sent yet. Not sure if this is v0 or v1

**Comment by DenioD** [comment]
after a message is sent, the rpc must refresh. This cause atm a gui refresh too, i will try to split it :-)
