### ISSUE TITLE
Create a pool of new zaddrs

### ISSUE THREAD

**Issue by DenioD** [DenioD/SilentDragonLite-1#28]
SDL should have a map of 10 new zaddrs, and give these away instead of creating everytime new ones.

**Comment by leto** [comment]
@DenioD does the lite server need to do anything or is this a local operation on the lite node, using it's seedphrase to generate 10 new addresses?

**Comment by DenioD** [comment]
sdl creates a zaddr with the sdl-cli lib. So its a local operation.

**Comment by leto** [comment]
@DenioD creating a set of new zaddrs to be pre-filled with funds for HushChat should not be that hard, if it's all local. sdl should create 10 new zaddrs, and then do a single ztx that splits funds evenly into them. That allows for 10 new contacts to be added and immediately chat with funds in that zaddr. 

When there is only 1 "new" zaddr left for a new contact, sdl should generate another 10 or somethng like that, which the user can decide on

**Comment by DenioD** [comment]
its not a absolutely necessary feature. Lets switch this to v1

**Comment by leto** [comment]
I was wrong, it's not a local operation to make new zaddrs and yes, this is a v1 issue

**Comment by leto** [comment]
not needed for SDL
