### ISSUE TITLE
Contact Request

### ISSUE THREAD

**Issue by DenioD** [DenioD/SilentDragonLite-1#35]
SDL should only have 1 contact request per zaddr, and delete it out of this perma map after adding this contact to Addressbook.

**Comment by leto** [comment]
@DenioD I am not sure I understand all the details going on here

**Comment by DenioD** [comment]
ATM, sdl dont delete a incoming contact request after you aggree/disaggree on it. It is still visible in this window. 

SDL should not render these "old" requests

**Comment by leto** [comment]
@DenioD ok, I understand now.

**Comment by DenioD** [comment]
SDL now distinguishes in new and old contactrequests. In future we are able to mark them as spam. But lets switch this feature to v1

**Comment by leto** [comment]
done!
