### ISSUE TITLE
New contact request with no funds doesn't work correctly

### ISSUE THREAD

**Issue by leto** [DenioD/SilentDragonLite-1#50]
![sdl-error](https://user-images.githubusercontent.com/30298/83048264-2b964780-9ffe-11ea-9fa9-f4b72fce6b30.png)

I got this error, but it still added my contact and that the request was sent, which isn't right

**Comment by leto** [comment]
we need this for v0, too many users will hit this

**Comment by DenioD** [comment]
fixed https://github.com/DenioD/SilentDragonLite-1/commit/8e59d777c2553bedb50bc75f173936f8e7ae7cfb   it will now, show the right error message, and sdl will not save the contact if the request was not successfully

**Comment by leto** [comment]
@DenioD thanks!!!! :beers:
