### ISSUE TITLE
Resizing window does not resize memo input area

### ISSUE THREAD

**Issue by leto** [DenioD/SilentDragonLite-1#53]
On Mac, if i resize the window, i can no longer see the text input.

We should have a dynamic, not a fixed width+height for the hushchat GUI

**Comment by leto** [comment]
This is not needed for v0

**Comment by leto** [comment]
@DenioD maybe i can help with this, i know it's one of your favorites :smiling_imp:

**Comment by DenioD** [comment]
i guess @sharpee is allready trying to fix, this. We need a Qt layout for the HusChat tab, so that we have a automatic resize :-)

**Comment by DenioD** [comment]
@sharpee fixed that problem :-)
