### ISSUE TITLE
Midnight theme is unusable

### ISSUE THREAD

**Issue by leto** [DenioD/SilentDragonLite-1#54]
black on black text

**Comment by leto** [comment]
@DenioD you don't need to fix this for v0, this can be v1. sharpee might want to fix it, too

**Comment by oDinZu** [comment]
@leto On restart, the text becomes white on black. There seems to be a bug when themes are switched. We don't have to restart in SD on theme switch, so I am unsure how this works for SDL.

I will update these things for midnight theme. The buttons need fixed also.

![MidnightTheme_Buttons](https://user-images.githubusercontent.com/18726788/83717191-1160f880-a600-11ea-8dc7-125be59b5297.PNG)

**Comment by DenioD** [comment]
ty @csharpee for fixing this!
