### ISSUE TITLE
Weird bug

### ISSUE THREAD

**Issue by leto** [DenioD/SilentDragonLite-1#59]
![weird-error](https://user-images.githubusercontent.com/30298/83172168-0d971880-a0cc-11ea-8133-f48b166857ca.png)

"Error connecting to hushd" is pretty weird from a Lite Wallet 

This was caused by putting a laptop to sleep and waking it up, the bane of our existence

**Comment by DenioD** [comment]
changed the error message to: "There was an error connecting to the server. Please check your internet connection. The error was:"  https://github.com/DenioD/SilentDragonLite-1/commit/e21a02a510e5a8274954030067cbbc3e3ab667df

**Comment by leto** [comment]
@DenioD you are a legend :metal:
