### ISSUE TITLE
Read old Addressbook properly

### ISSUE THREAD

**Issue by DenioD** [DenioD/SilentDragonLite-1#61]
SDL will dump at the moment, if you start it with a old addressbooklabels.dat. We need to read the file and convert it to the new format.

**Comment by DenioD** [comment]
this is for v0

**Comment by DenioD** [comment]
Done for addressbook v1 to v2 (sdl normal to sdl chat). Addressbooklabels.dat of the closed alpha (before this commit)  isnt supportet atm.  https://github.com/DenioD/SilentDragonLite-1/commit/4413d3de62a1504c27f94ba7a8462f5dd8faecd2

**Comment by leto** [comment]
We now just move it out of the way and start fresh. This is low priority unless we get users that need to import old addressbooks
