### ISSUE TITLE
Verify Seed

### ISSUE THREAD

**Issue by leto** [DenioD/SilentDragonLite-1#63]
We need to make sure the user has written down their seed, so we need to make them verify it somehow.

One way is to make them type it all in, there are others. We could skip this for v0 but we definitely need it for v1.

Another way is to show them all their seed words in the incorrect order, and make them drag+drop them into the correct order. This is more work for us, but makes it so users don't have to type the whole seedphrase.

**Comment by oDinZu** [comment]
It would also be super if we could have a create new seed button, rather than have to use the seed provided to the user on first setup.

**Comment by leto** [comment]
@csharpee I don't quite understand that, please make a new issue for v1 or later on the main SDL repo
