### ISSUE TITLE
Set passphrase on initial install

### ISSUE THREAD

**Issue by leto** [DenioD/SilentDragonLite-1#64]
As of my binary, a brand new install does not encrypt by default.

We should force the user to set a passphrase during install, just after they verify their seed.

We could skip this for v0 but we need it for v1. I don't think we should allow people to not have a passphrase, it should be mandatory.

**Comment by DenioD** [comment]
we should switch that to v0, since we need the user to encrypt his wallet, for our new messages encryption

**Comment by DenioD** [comment]
done
