### ISSUE TITLE
Weird error again

### ISSUE THREAD

**Issue by leto** [DenioD/SilentDragonLite-1#68]
![latest-block-error](https://user-images.githubusercontent.com/30298/83178870-0412ae00-a0d6-11ea-90f9-73b52a72f227.png)

I am not trying to send a transaction, but this error pops up occasionally. 

Not exactly sure what is up

**Comment by DenioD** [comment]
Our switch to one server should resolve this issue

**Comment by leto** [comment]
@DenioD plz assign this to me. I don't have admin rights on this repo so I can't

**Comment by leto** [comment]
I need to remove an IP from CloudFlare and then this should be resolved.

**Comment by leto** [comment]
I am not seeing this anymore, closing for now
