### ISSUE TITLE
It is possible to uncheck a radiobutton on initial create/restore dialog

### ISSUE THREAD

**Issue by ab-obo** [DenioD/SilentDragonLite-1#70]
On 'next' button press it starts a 'restore' dialog (if nothing is checked)
![image](https://user-images.githubusercontent.com/9332836/83201825-06651e80-a14f-11ea-8f0b-81206e22a10e.png)

**Comment by leto** [comment]
good find @ab-obo

**Comment by DenioD** [comment]
ty @ab-obo

**Comment by leto** [comment]
@DenioD likely you are using 2 toggles where you need to use one set of "radio" buttons. Not sure what QT calls them but that is what HTML calls them
