### ISSUE TITLE
Can send a message even though no recipient has been chosen

### ISSUE THREAD

**Issue by heguli97** [DenioD/SilentDragonLite-1#81]
Open SDL > Go to HushChat tab > Type some message > Press send > A transaction happens

When opening chat tab and no contact has been chosen you can still "send" a message even though you haven't chosen a recipient. A empty transaction gets made, but no memo gets sent(doesn't matter since there's no recipient).

OS: Win 10 x64

**Comment by oDinZu** [comment]
Operating System: Windows 10 Pro 64bit
Application Version: SDL v1.3-Chat-Alpha

This looks to be fixed when testing this today. 
Note: I do not have any funds or contacts added and the following screen populated.

![Midnight_errordialog_nofundsContacts](https://user-images.githubusercontent.com/18726788/83717406-a2d06a80-a600-11ea-9643-4853d004b70c.PNG)

**Comment by heguli97** [comment]
I can confirm it is indeed fixed in the latest binary.
![empty send fixed](https://user-images.githubusercontent.com/38728905/83923334-af80ca00-a78a-11ea-9521-c4b8260448aa.png)

**Comment by heguli97** [comment]
Looks like i can still replicate this bug on the latest binary version

Keep in mind you need to have some hush in the wallet to make the empty memo transaction :)

**Comment by DenioD** [comment]
fixed
