### ISSUE TITLE
Date formatting madness

### ISSUE THREAD

**Issue by leto** [DenioD/SilentDragonLite-1#82]
Currently the dates look weird to me, because I am not European.

Let's standardize on a date format https://en.wikipedia.org/wiki/ISO_8601

I am not a fan of the `T`, so lets use a space:

`2020-05-29 22:23:33`

This ignores timezone which is another issue

**Comment by DenioD** [comment]
That looks weird to europeans, but its ISO, so lets change it

**Comment by leto** [comment]
@DenioD later on, we can make settings to render dates custom for users, but for now, ISO should hopefully confuse the fewest people worldwide :smile:

**Comment by DenioD** [comment]
done :-)
