### ISSUE TITLE
Are timestamps rendering in local TZ or UTC?

### ISSUE THREAD

**Issue by leto** [DenioD/SilentDragonLite-1#83]
It's not clear if timestamps are UTC or local TZ, it should specify.

We probably should have a config settings that says "Should timestamps be rendered in UTC or local TZ?"

**Comment by DenioD** [comment]
It should take the local TZ. But i will make a new menu config, so the user can decide which format he wants

**Comment by leto** [comment]
@DenioD that sounds cool! And lets push that to v1 :smile:
