### ISSUE TITLE
Remove "Your message will be sent" popup

### ISSUE THREAD

**Issue by leto** [DenioD/SilentDragonLite-1#84]
For sending transactions, I like the popup with notifications of what is happening.

For our chat GUI, I think it's more appropriate to have no popups at all, and just have a little spinner icon, a moving/spinning icon, indicating that the memo is being sent out. If there is an error, we should show an error icon that can be clicked, to inspect the error.

So the new flow, is that I type a memo, press send, and it's immediately rendered as a chatItem with a "spinner" that completes, and turns into a "sent lock" when we have broadcast the tx.

This feels important for UI, but we can push it to v1 if necessary.

**Comment by oDinZu** [comment]
Yeah, I like this idea @leto This will provide more flow. Creating that GIF will be a lot of work if we manually do this; maybe Berg will be able to aid in this? If not, I am sure there are some freebies out there that hopefully match our themes.

**Comment by leto** [comment]
@csharpee I am sure we can use some existing stock spinner

**Comment by DenioD** [comment]
done
