### ISSUE TITLE
Generate New Address Copies Ugly Content - Needs to just copy address

### ISSUE THREAD

**Issue by UrgeyBergy** [DenioD/SilentDragonLite-1#89]
Popup is not necessary, could just display a tooltip that hovers over the zs1 logo for roughly 3 seconds after clicking that reads "Copied to Clipboard!"
Below is what is currently copied from the popup, where you have to manually delete extra dashes and the ok button text, etc. after pasting. See below:

---------------------------
Your new Hushchataddress
---------------------------
zs1aeahddrlfzqxyy3lvcs6g3evqhl73c822c9a40evt6v4j0hpn8zu46hjhd78k283mlwpvewejlm
---------------------------
OK   
---------------------------

Test address used:
![image](https://user-images.githubusercontent.com/37842843/83582815-9240c700-a510-11ea-9398-8f16cc00e76c.png)

**Comment by DenioD** [comment]
done https://github.com/DenioD/SilentDragonLite-1/commit/32a706339cd8f22147cd3c697c525c42868807de
