### ISSUE TITLE
GUI Elements Overlap by Default on Incoming Contact Request Screen

### ISSUE THREAD

**Issue by oDinZu** [DenioD/SilentDragonLite-1#92]
Operating System: Windows 10 Pro 64bit
Application Version: SDL v1.3-Chat-Alpha
Theme: All

See screenshot below
![IncomingRequestDefaultScreen](https://user-images.githubusercontent.com/18726788/83716587-508e4a00-a5fe-11ea-8905-0a92417190e3.PNG)

**Comment by DenioD** [comment]
Can you check, if you have still this issue? It should normaly dont do it, cause this window has a layout. If you have still this issue, at what resolution do you have that?

**Comment by leto** [comment]
@csharpee does this issue still exist in latest bins?

**Comment by oDinZu** [comment]
Yes

**Comment by leto** [comment]
This seems important for v0

**Comment by DenioD** [comment]
could you provide your resolution @csharpee? i cannot reproduce this issue, the resolution you use would be helpfull.

**Comment by leto** [comment]
If this is rare or not easy to reproduce, it does not need to be fixed for v0

**Comment by oDinZu** [comment]
@DenioD My resolution is 1920x1080. I may be able to fix this. Looks like min width has been set causing the overlapping.

When the application popup screen is reduced horz. in size to its minimum, you should be able to reproduce this GUI bug.

**Comment by oDinZu** [comment]
I also noticed 3 invisible items with requestCID, zaddrnew and zaddrold. Do we need these for this screen? 
![Screenshot from 2020-06-08 00-07-24](https://user-images.githubusercontent.com/18726788/83991876-3ca75880-a91c-11ea-9790-96de4a1fcd18.png)
@DenioD

**Comment by DenioD** [comment]
thats weird, i have the same resoultion...hmm so not easy to reproduce for me. Yes we need them @csharpee

**Comment by oDinZu** [comment]
Okay, I have fixed it and a couple other typos, simplified add new contact, plus fixed avatar alignment. I sent the min width of the requestDialog QDialog to 850 and sizePolicy for horz to Minimum.

Okay, PR has been sent.

![Screenshot from 2020-06-08 00-24-16](https://user-images.githubusercontent.com/18726788/83992469-6a8d9c80-a91e-11ea-8110-7198b11a840a.png)

**Comment by csharpee** [comment]
Okay, PR has been sent.

**Comment by DenioD** [comment]
fixed by @csharpee ty!
