### ISSUE TITLE
On Encryption of Wallet, No Dialog Box for Success or User Feedback

### ISSUE THREAD

**Issue by oDinZu** [DenioD/SilentDragonLite-1#95]
Operating System: Windows 10 Pro 64bit
Application Version: SDL v1.3-Chat-Alpha

A nice to have thing for feedback. After wallet has been encrypted, provide dialog box of successfully encrypted wallet.

I.E. Your HushChat Wallet Has Been Encrypted; please restart to verify encrypted wallet.

**Comment by oDinZu** [comment]
Also, on decryption of wallet, we have a popup for feedback. 
Please correct spelling to say: Successfully removed encryption from wallet or keep what you have and add Successfully delete**d** the encryption.

![Capture](https://user-images.githubusercontent.com/18726788/83718262-b67cd080-a602-11ea-9560-7e8800d6e766.PNG)

Also, capitalization of `decryption to Decryption` to match capitalization of other two words.

**Comment by DenioD** [comment]
done
