### ISSUE TITLE
Sluggish Transaction Screen after  Resize + Many Transactions

### ISSUE THREAD

**Issue by oDinZu** [DenioD/SilentDragonLite-1#96]
Operating System: Linux Ubuntu 20.04
Application Version: SDL v1.3-Chat-Alpha

On transaction screen, many transactions creates a very sluggish or lag on resize of the wallet.

**Comment by leto** [comment]
@csharpee this is useful input, but this is not an actionable issue. If you think there is a legit bug, please submit a detailed report of it
